name: hykolab
description: "Smart Tank Hunian sebagai Solusi Mikro untuk Mitigasi Penurunan Tanah"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  fl_chart: ^1.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: "icons/app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  
  # Folder untuk menyimpan assets
  assets:
    - assets/images/