name: hykolab
description: "Smart Tank Hunian sebagai Solusi Mikro untuk Mitigasi Penurunan Tanah"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Folder untuk menyimpan assets
  assets:
    - assets/images/